language: node_js
cache: yarn
jobs:
  include:
  - stage: test
    script: yarn lint && yarn test-single && codecov
  - stage: npm-bundle
    script: yarn build && npm version $TRAVIS_BRANCH --allow-same-version --allow-empty
    deploy:
      edge: true
      provider: npm
      email: bameyrick@gmail.com
      api_key:
        secure: bE5Z+93MtAR9vLrH8Ortk0nvADKdSlI1qS+/NYKIWxWI1oG2ut58dZQGASHcaOCa/ytxkiMn+kFicLG7NuThgEfODkQJMFDXjhNXWP98I5OBPwv9GtbYa1OhvpSvULHQ8AfQs/b6/YiVziLWkz7w/efpGXRMSPGtHRpQ5RLYXOsrqyTB1Zike/vbzuZh9ZGm/GdC1xsJZhHZeBVMHO8CN6zPdIdq84IYKzBdWFJVrrEEDF5Nrs3NVUhuEsU1bixvkKIfX4ImdXhAbaatwGq61jZiBerwAfb28JwjbrGVNThMTNIhHdCAAifxFpPVwiFjqoBbGr7QLRo/ZCsLWy7uIi0xEvVtmnA6Lk4LAX2rnrylSLU+6b4YvGru+VJuOKbNkLAIj34NOd3EhVhksUDMkvhB8wZWhc4vQDGtes+7tXrI1GSTjgvEnUdxr5z5kEucbyYaQSiwnzgRTL+Rb9/BhfzxSPpZJ7Ydv085d/O+Nsia2ycDCNSC+RUNoAD4pP+iFVS6sk7lB2dzX2mkxTayPAPE+5oYMVJYSECYaDtLSjxJqBt98vir3S/X3RvBdXLaRV+SXr5TwZt1uwWA6CB0OY9cKTGKcBV1nQYjCNqouXZiVwflYdNjf+G3hRnFgP9iEvAiAFxkVUnveJtZVhUPzb+QVtrxZAUsgzoHH0xcTEA=
      on:
        tags: true
stages:
- name: test
  if: tag IS NOT present
- name: npm-bundle
  if: tag IS present
